apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-world
  labels:
    app: world
spec:
  replicas: 1
  selector:
    matchLabels:
      app: world
  template:
    metadata:
      labels:
        app: world
    spec:
      containers:
        - name: world
          image: kartikchindarkar/world:latest
          ports:
            - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: k8s-world-service
spec:
  type: LoadBalancer
  selector:
    app: world
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081